version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  package:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm build
workflows:
    step-1:
      jobs:
        - build-and-test
        - package:
            requires:
                - build-and-test