version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10

jobs:
  build-and-test-job:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  package-job:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm build

workflows:
  build-and-test:
    jobs:
      - build-and-test-job
      - package-job:
          requires:
            - build-and-test-job

  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
        filters:
          branches:
            only: 
              - master
